# Generated by Django 6.0 on 2025-12-12 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='RUT con puntos y guión', max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('es_empresa', models.BooleanField(default=False, help_text='¿Es flota o empresa?')),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_area', models.CharField(choices=[('LAB', 'Laboratorio Diesel (Banco de Pruebas)'), ('MEC', 'Mecánica General (Patio)'), ('LAV', 'Zona de Lavado')], max_length=3)),
                ('encargado', models.CharField(help_text='Jefe de taller o encargado del área', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('vin', models.CharField(blank=True, max_length=30, null=True, verbose_name='Número de Chasis/VIN')),
                ('tipo_motor', models.CharField(blank=True, help_text='Ej: Common Rail, Convencional, Electrónico', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='api_diesel.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(choices=[('PREV', 'Mantención Preventiva'), ('INY', 'Reparación/Calibración Inyectores'), ('BOM', 'Reparación/Calibración Bomba'), ('MEC', 'Mecánica (Sacar/Poner)'), ('LAV', 'Lavado de Estanque'), ('COMP', 'Servicio Completo (Mecánica + Laboratorio)')], max_length=4)),
                ('estado', models.CharField(choices=[('ING', 'Ingresado / En Espera'), ('DIAG', 'En Diagnóstico'), ('REP', 'En Reparación / Calibración'), ('ESP', 'Esperando Repuestos'), ('LISTO', 'Listo para Entrega'), ('ENTR', 'Entregado')], default='ING', max_length=5)),
                ('descripcion_falla', models.TextField(help_text='Lo que el cliente dice que falla')),
                ('observaciones_tecnicas', models.TextField(blank=True, help_text='Diagnóstico del mecánico/bombero')),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('nivel_combustible', models.CharField(blank=True, choices=[('RES', 'Reserva'), ('1/4', 'Un Cuarto'), ('1/2', 'Medio Estanque'), ('3/4', 'Tres Cuartos'), ('FULL', 'Lleno')], max_length=4, null=True)),
                ('costo_total', models.PositiveIntegerField(default=0, help_text='Valor en pesos chilenos')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_diesel.cliente')),
                ('taller', models.ForeignKey(help_text='Área responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_diesel.taller')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_diesel.vehiculo')),
            ],
        ),
    ]
